#ifndef _TYPES_H
#define _TYPES_H

#ifndef BOOL
typedef int             BOOL;
#endif

#ifndef IN
#define IN
#endif

#ifndef OUT
#define OUT
#endif

typedef unsigned int    UINT;
typedef int             INT;

#define FALSE   0
#define TRUE    1

/******************************************************************************\
******************************** Ceiling Macro ********************************
\******************************************************************************/
#define gcmCEIL(x) ((x - (gctUINT32)x) == 0 ? (gctUINT32)x : (gctUINT32)x + 1)

/******************************************************************************\
******************************** Min/Max Macros ********************************
\******************************************************************************/

#define gcmMIN(x, y)            (((x) <= (y)) ?  (x) :  (y))
#define gcmMAX(x, y)            (((x) >= (y)) ?  (x) :  (y))
#define gcmCLAMP(x, min, max)   (((x) < (min)) ? (min) : \
                                 ((x) > (max)) ? (max) : (x))
#define gcmABS(x)               (((x) < 0)    ? -(x) :  (x))
#define gcmNEG(x)               (((x) < 0)    ?  (x) : -(x))

/* Surface formats. */
typedef enum _gceSURF_FORMAT
{
    /* Unknown format. */
    gcvSURF_UNKNOWN             = 0,

    /* Palettized formats. */
    gcvSURF_INDEX1              = 100,
    gcvSURF_INDEX4,
    gcvSURF_INDEX8,

    /* RGB formats. */
    gcvSURF_A2R2G2B2            = 200,
    gcvSURF_R3G3B2,
    gcvSURF_A8R3G3B2,
    gcvSURF_X4R4G4B4,
    gcvSURF_A4R4G4B4,
    gcvSURF_R4G4B4A4,
    gcvSURF_X1R5G5B5,
    gcvSURF_A1R5G5B5,
    gcvSURF_R5G5B5A1,
    gcvSURF_R5G6B5,
    gcvSURF_R8G8B8,
    gcvSURF_X8R8G8B8,
    gcvSURF_A8R8G8B8,
    gcvSURF_R8G8B8A8,
    gcvSURF_G8R8G8B8,
    gcvSURF_R8G8B8G8,
    gcvSURF_X2R10G10B10,
    gcvSURF_A2R10G10B10,
    gcvSURF_X12R12G12B12,
    gcvSURF_A12R12G12B12,
    gcvSURF_X16R16G16B16,
    gcvSURF_A16R16G16B16,
    gcvSURF_A32R32G32B32,
    gcvSURF_R8G8B8X8,
    gcvSURF_R5G5B5X1,
    gcvSURF_R4G4B4X4,

    /* BGR formats. */
    gcvSURF_A4B4G4R4            = 300,
    gcvSURF_A1B5G5R5,
    gcvSURF_B5G6R5,
    gcvSURF_B8G8R8,
    gcvSURF_B16G16R16,
    gcvSURF_X8B8G8R8,
    gcvSURF_A8B8G8R8,
    gcvSURF_A2B10G10R10,
    gcvSURF_X16B16G16R16,
    gcvSURF_A16B16G16R16,
    gcvSURF_B32G32R32,
    gcvSURF_X32B32G32R32,
    gcvSURF_A32B32G32R32,
    gcvSURF_B4G4R4A4,
    gcvSURF_B5G5R5A1,
    gcvSURF_B8G8R8X8,
    gcvSURF_B8G8R8A8,
    gcvSURF_X4B4G4R4,
    gcvSURF_X1B5G5R5,
    gcvSURF_B4G4R4X4,
    gcvSURF_B5G5R5X1,
    gcvSURF_X2B10G10R10,

    /* Compressed formats. */
    gcvSURF_DXT1                = 400,
    gcvSURF_DXT2,
    gcvSURF_DXT3,
    gcvSURF_DXT4,
    gcvSURF_DXT5,
    gcvSURF_CXV8U8,
    gcvSURF_ETC1,
    gcvSURF_R11_EAC,
    gcvSURF_SIGNED_R11_EAC,
    gcvSURF_RG11_EAC,
    gcvSURF_SIGNED_RG11_EAC,
    gcvSURF_RGB8_ETC2,
    gcvSURF_SRGB8_ETC2,
    gcvSURF_RGB8_PUNCHTHROUGH_ALPHA1_ETC2,
    gcvSURF_SRGB8_PUNCHTHROUGH_ALPHA1_ETC2,
    gcvSURF_RGBA8_ETC2_EAC,
    gcvSURF_SRGB8_ALPHA8_ETC2_EAC,

    /* YUV formats. */
    gcvSURF_YUY2                = 500,
    gcvSURF_UYVY,
    gcvSURF_YV12,
    gcvSURF_I420,
    gcvSURF_NV12,
    gcvSURF_NV21,
    gcvSURF_NV16,
    gcvSURF_NV61,
    gcvSURF_YVYU,
    gcvSURF_VYUY,

    /* Depth formats. */
    gcvSURF_D16                 = 600,
    gcvSURF_D24S8,
    gcvSURF_D32,
    gcvSURF_D24X8,

    /* Alpha formats. */
    gcvSURF_A4                  = 700,
    gcvSURF_A8,
    gcvSURF_A12,
    gcvSURF_A16,
    gcvSURF_A32,
    gcvSURF_A1,

    /* Luminance formats. */
    gcvSURF_L4                  = 800,
    gcvSURF_L8,
    gcvSURF_L12,
    gcvSURF_L16,
    gcvSURF_L32,
    gcvSURF_L1,

    /* Alpha/Luminance formats. */
    gcvSURF_A4L4                = 900,
    gcvSURF_A2L6,
    gcvSURF_A8L8,
    gcvSURF_A4L12,
    gcvSURF_A12L12,
    gcvSURF_A16L16,

    /* Bump formats. */
    gcvSURF_L6V5U5              = 1000,
    gcvSURF_V8U8,
    gcvSURF_X8L8V8U8,
    gcvSURF_Q8W8V8U8,
    gcvSURF_A2W10V10U10,
    gcvSURF_V16U16,
    gcvSURF_Q16W16V16U16,

    /* R/RG/RA formats. */
    gcvSURF_R8                  = 1100,
    gcvSURF_X8R8,
    gcvSURF_G8R8,
    gcvSURF_X8G8R8,
    gcvSURF_A8R8,
    gcvSURF_R16,
    gcvSURF_X16R16,
    gcvSURF_G16R16,
    gcvSURF_X16G16R16,
    gcvSURF_A16R16,
    gcvSURF_R32,
    gcvSURF_X32R32,
    gcvSURF_G32R32,
    gcvSURF_X32G32R32,
    gcvSURF_A32R32,
    gcvSURF_RG16,

    /* Floating point formats. */
    gcvSURF_R16F                = 1200,
    gcvSURF_X16R16F,
    gcvSURF_G16R16F,
    gcvSURF_X16G16R16F,
    gcvSURF_B16G16R16F,
    gcvSURF_X16B16G16R16F,
    gcvSURF_A16B16G16R16F,
    gcvSURF_R32F,
    gcvSURF_X32R32F,
    gcvSURF_G32R32F,
    gcvSURF_X32G32R32F,
    gcvSURF_B32G32R32F,
    gcvSURF_X32B32G32R32F,
    gcvSURF_A32B32G32R32F,
    gcvSURF_A16F,
    gcvSURF_L16F,
    gcvSURF_A16L16F,
    gcvSURF_A16R16F,
    gcvSURF_A32F,
    gcvSURF_L32F,
    gcvSURF_A32L32F,
    gcvSURF_A32R32F,

    gcvSURF_A8R8G8B8_HZ         = 1400,
} gceSURF_FORMAT;

typedef enum _gceSTATUS
{
    gcvSTATUS_OK                    =   0,
    gcvSTATUS_FALSE                 =   0,
    gcvSTATUS_TRUE                  =   1,
    gcvSTATUS_NO_MORE_DATA          =   2,
    gcvSTATUS_CACHED                =   3,
    gcvSTATUS_MIPMAP_TOO_LARGE      =   4,
    gcvSTATUS_NAME_NOT_FOUND        =   5,
    gcvSTATUS_NOT_OUR_INTERRUPT     =   6,
    gcvSTATUS_MISMATCH              =   7,
    gcvSTATUS_MIPMAP_TOO_SMALL      =   8,
    gcvSTATUS_LARGER                =   9,
    gcvSTATUS_SMALLER               =   10,
    gcvSTATUS_CHIP_NOT_READY        =   11,
    gcvSTATUS_NEED_CONVERSION       =   12,
    gcvSTATUS_SKIP                  =   13,
    gcvSTATUS_DATA_TOO_LARGE        =   14,
    gcvSTATUS_INVALID_CONFIG        =   15,
    gcvSTATUS_CHANGED               =   16,
    gcvSTATUS_NOT_SUPPORT_DITHER    =   17,
    gcvSTATUS_EXECUTED              =    18,
    gcvSTATUS_TERMINATE             =   19,

    gcvSTATUS_CONVERT_TO_SINGLE_STREAM    =   20,

    gcvSTATUS_INVALID_ARGUMENT      =   -1,
    gcvSTATUS_INVALID_OBJECT        =   -2,
    gcvSTATUS_OUT_OF_MEMORY         =   -3,
    gcvSTATUS_MEMORY_LOCKED         =   -4,
    gcvSTATUS_MEMORY_UNLOCKED       =   -5,
    gcvSTATUS_HEAP_CORRUPTED        =   -6,
    gcvSTATUS_GENERIC_IO            =   -7,
    gcvSTATUS_INVALID_ADDRESS       =   -8,
    gcvSTATUS_CONTEXT_LOSSED        =   -9,
    gcvSTATUS_TOO_COMPLEX           =   -10,
    gcvSTATUS_BUFFER_TOO_SMALL      =   -11,
    gcvSTATUS_INTERFACE_ERROR       =   -12,
    gcvSTATUS_NOT_SUPPORTED         =   -13,
    gcvSTATUS_MORE_DATA             =   -14,
    gcvSTATUS_TIMEOUT               =   -15,
    gcvSTATUS_OUT_OF_RESOURCES      =   -16,
    gcvSTATUS_INVALID_DATA          =   -17,
    gcvSTATUS_INVALID_MIPMAP        =   -18,
    gcvSTATUS_NOT_FOUND             =   -19,
    gcvSTATUS_NOT_ALIGNED           =   -20,
    gcvSTATUS_INVALID_REQUEST       =   -21,
    gcvSTATUS_GPU_NOT_RESPONDING    =   -22,
    gcvSTATUS_TIMER_OVERFLOW        =   -23,
    gcvSTATUS_VERSION_MISMATCH      =   -24,
    gcvSTATUS_LOCKED                =   -25,
    gcvSTATUS_INTERRUPTED           =   -26,
    gcvSTATUS_DEVICE                =   -27,
    gcvSTATUS_NOT_MULTI_PIPE_ALIGNED =   -28,

    /* Linker errors. */
    gcvSTATUS_GLOBAL_TYPE_MISMATCH  =   -1000,
    gcvSTATUS_TOO_MANY_ATTRIBUTES   =   -1001,
    gcvSTATUS_TOO_MANY_UNIFORMS     =   -1002,
    gcvSTATUS_TOO_MANY_VARYINGS     =   -1003,
    gcvSTATUS_UNDECLARED_VARYING    =   -1004,
    gcvSTATUS_VARYING_TYPE_MISMATCH =   -1005,
    gcvSTATUS_MISSING_MAIN          =   -1006,
    gcvSTATUS_NAME_MISMATCH         =   -1007,
    gcvSTATUS_INVALID_INDEX         =   -1008,
    gcvSTATUS_UNIFORM_TYPE_MISMATCH =   -1009,

    /* Compiler errors. */
    gcvSTATUS_COMPILER_FE_PREPROCESSOR_ERROR = -2000,
    gcvSTATUS_COMPILER_FE_PARSER_ERROR = -2001,
} gceSTATUS;

typedef enum _GLESAPIIndex
{
    /* ES3.0/ES2.0 functions */
    GL3_API_glVertexAttribPointer = 0,
    GL3_API_glUniform4fv,
    GL3_API_glBindBuffer,
    GL3_API_glUseProgram,
    GL3_API_glUniformMatrix4fv,
    GL3_API_glDrawElements,
    GL3_API_glBindTexture,
    GL3_API_glActiveTexture,
    GL3_API_glDisableVertexAttribArray,
    GL3_API_glEnableVertexAttribArray,
    GL3_API_glEnable,
    GL3_API_glBufferSubData,
    GL3_API_glGetIntegerv,
    GL3_API_glAttachShader,
    GL3_API_glBindAttribLocation,
    GL3_API_glBindFramebuffer,
    GL3_API_glBindRenderbuffer,
    GL3_API_glBlendColor,
    GL3_API_glBlendEquation,
    GL3_API_glBlendEquationSeparate,
    GL3_API_glBlendFunc,
    GL3_API_glBlendFuncSeparate,
    GL3_API_glBufferData,
    GL3_API_glCheckFramebufferStatus,
    GL3_API_glClear,
    GL3_API_glClearColor,
    GL3_API_glClearDepthf,
    GL3_API_glClearStencil,
    GL3_API_glColorMask,
    GL3_API_glCompileShader,
    GL3_API_glCompressedTexImage2D,
    GL3_API_glCompressedTexSubImage2D,
    GL3_API_glCopyTexImage2D,
    GL3_API_glCopyTexSubImage2D,
    GL3_API_glCreateProgram,
    GL3_API_glCreateShader,
    GL3_API_glCullFace,
    GL3_API_glDeleteBuffers,
    GL3_API_glDeleteFramebuffers,
    GL3_API_glDeleteTextures,
    GL3_API_glDeleteProgram,
    GL3_API_glDeleteRenderbuffers,
    GL3_API_glDeleteShader,
    GL3_API_glDetachShader,
    GL3_API_glDepthFunc,
    GL3_API_glDepthMask,
    GL3_API_glDepthRangef,
    GL3_API_glDisable,
    GL3_API_glDrawArrays,
    GL3_API_glFinish,
    GL3_API_glFlush,
    GL3_API_glFramebufferRenderbuffer,
    GL3_API_glFramebufferTexture2D,
    GL3_API_glFrontFace,
    GL3_API_glGenBuffers,
    GL3_API_glGenerateMipmap,
    GL3_API_glGenFramebuffers,
    GL3_API_glGenRenderbuffers,
    GL3_API_glGenTextures,
    GL3_API_glGetActiveAttrib,
    GL3_API_glGetActiveUniform,
    GL3_API_glGetAttachedShaders,
    GL3_API_glGetAttribLocation,
    GL3_API_glGetBooleanv,
    GL3_API_glGetBufferParameteriv,
    GL3_API_glGetError,
    GL3_API_glGetFloatv,
    GL3_API_glGetFramebufferAttachmentParameteriv,
    GL3_API_glGetProgramiv,
    GL3_API_glGetProgramInfoLog,
    GL3_API_glGetRenderbufferParameteriv,
    GL3_API_glGetShaderiv,
    GL3_API_glGetShaderInfoLog,
    GL3_API_glGetShaderPrecisionFormat,
    GL3_API_glGetShaderSource,
    GL3_API_glGetString,
    GL3_API_glGetTexParameterfv,
    GL3_API_glGetTexParameteriv,
    GL3_API_glGetUniformfv,
    GL3_API_glGetUniformiv,
    GL3_API_glGetUniformLocation,
    GL3_API_glGetVertexAttribfv,
    GL3_API_glGetVertexAttribiv,
    GL3_API_glGetVertexAttribPointerv,
    GL3_API_glHint,
    GL3_API_glIsBuffer,
    GL3_API_glIsEnabled,
    GL3_API_glIsFramebuffer,
    GL3_API_glIsProgram,
    GL3_API_glIsRenderbuffer,
    GL3_API_glIsShader,
    GL3_API_glIsTexture,
    GL3_API_glLineWidth,
    GL3_API_glLinkProgram,
    GL3_API_glPixelStorei,
    GL3_API_glPolygonOffset,
    GL3_API_glReadPixels,
    GL3_API_glReleaseShaderCompiler,
    GL3_API_glRenderbufferStorage,
    GL3_API_glSampleCoverage,
    GL3_API_glScissor,
    GL3_API_glShaderBinary,
    GL3_API_glShaderSource,
    GL3_API_glStencilFunc,
    GL3_API_glStencilFuncSeparate,
    GL3_API_glStencilMask,
    GL3_API_glStencilMaskSeparate,
    GL3_API_glStencilOp,
    GL3_API_glStencilOpSeparate,
    GL3_API_glTexImage2D,
    GL3_API_glTexParameterf,
    GL3_API_glTexParameterfv,
    GL3_API_glTexParameteri,
    GL3_API_glTexParameteriv,
    GL3_API_glTexSubImage2D,
    GL3_API_glUniform1f,
    GL3_API_glUniform1fv,
    GL3_API_glUniform1i,
    GL3_API_glUniform1iv,
    GL3_API_glUniform2f,
    GL3_API_glUniform2fv,
    GL3_API_glUniform2i,
    GL3_API_glUniform2iv,
    GL3_API_glUniform3f,
    GL3_API_glUniform3fv,
    GL3_API_glUniform3i,
    GL3_API_glUniform3iv,
    GL3_API_glUniform4f,
    GL3_API_glUniform4i,
    GL3_API_glUniform4iv,
    GL3_API_glUniformMatrix2fv,
    GL3_API_glUniformMatrix3fv,
    GL3_API_glValidateProgram,
    GL3_API_glVertexAttrib1f,
    GL3_API_glVertexAttrib1fv,
    GL3_API_glVertexAttrib2f,
    GL3_API_glVertexAttrib2fv,
    GL3_API_glVertexAttrib3f,
    GL3_API_glVertexAttrib3fv,
    GL3_API_glVertexAttrib4f,
    GL3_API_glVertexAttrib4fv,
    GL3_API_glViewport,
    GL3_API_glReadBuffer,
    GL3_API_glDrawRangeElements,
    GL3_API_glTexImage3D,
    GL3_API_glTexSubImage3D,
    GL3_API_glCopyTexSubImage3D,
    GL3_API_glCompressedTexImage3D,
    GL3_API_glCompressedTexSubImage3D,
    GL3_API_glGenQueries,
    GL3_API_glDeleteQueries,
    GL3_API_glIsQuery,
    GL3_API_glBeginQuery,
    GL3_API_glEndQuery,
    GL3_API_glGetQueryiv,
    GL3_API_glGetQueryObjectuiv,
    GL3_API_glUnmapBuffer,
    GL3_API_glGetBufferPointerv,
    GL3_API_glDrawBuffers,
    GL3_API_glUniformMatrix2x3fv,
    GL3_API_glUniformMatrix3x2fv,
    GL3_API_glUniformMatrix2x4fv,
    GL3_API_glUniformMatrix4x2fv,
    GL3_API_glUniformMatrix3x4fv,
    GL3_API_glUniformMatrix4x3fv,
    GL3_API_glBlitFramebuffer,
    GL3_API_glRenderbufferStorageMultisample,
    GL3_API_glFramebufferTextureLayer,
    GL3_API_glMapBufferRange,
    GL3_API_glFlushMappedBufferRange,
    GL3_API_glBindVertexArray,
    GL3_API_glDeleteVertexArrays,
    GL3_API_glGenVertexArrays,
    GL3_API_glIsVertexArray,
    GL3_API_glGetIntegeri_v,
    GL3_API_glBeginTransformFeedback,
    GL3_API_glEndTransformFeedback,
    GL3_API_glBindBufferRange,
    GL3_API_glBindBufferBase,
    GL3_API_glTransformFeedbackVaryings,
    GL3_API_glGetTransformFeedbackVarying,
    GL3_API_glVertexAttribIPointer,
    GL3_API_glGetVertexAttribIiv,
    GL3_API_glGetVertexAttribIuiv,
    GL3_API_glVertexAttribI4i,
    GL3_API_glVertexAttribI4ui,
    GL3_API_glVertexAttribI4iv,
    GL3_API_glVertexAttribI4uiv,
    GL3_API_glGetUniformuiv,
    GL3_API_glGetFragDataLocation,
    GL3_API_glUniform1ui,
    GL3_API_glUniform2ui,
    GL3_API_glUniform3ui,
    GL3_API_glUniform4ui,
    GL3_API_glUniform1uiv,
    GL3_API_glUniform2uiv,
    GL3_API_glUniform3uiv,
    GL3_API_glUniform4uiv,
    GL3_API_glClearBufferiv,
    GL3_API_glClearBufferuiv,
    GL3_API_glClearBufferfv,
    GL3_API_glClearBufferfi,
    GL3_API_glGetStringi,
    GL3_API_glCopyBufferSubData,
    GL3_API_glGetUniformIndices,
    GL3_API_glGetActiveUniformsiv,
    GL3_API_glGetUniformBlockIndex,
    GL3_API_glGetActiveUniformBlockiv,
    GL3_API_glGetActiveUniformBlockName,
    GL3_API_glUniformBlockBinding,
    GL3_API_glDrawArraysInstanced,
    GL3_API_glDrawElementsInstanced,
    GL3_API_glFenceSync,
    GL3_API_glIsSync,
    GL3_API_glDeleteSync,
    GL3_API_glClientWaitSync,
    GL3_API_glWaitSync,
    GL3_API_glGetInteger64v,
    GL3_API_glGetSynciv,
    GL3_API_glGetInteger64i_v,
    GL3_API_glGetBufferParameteri64v,
    GL3_API_glGenSamplers,
    GL3_API_glDeleteSamplers,
    GL3_API_glIsSampler,
    GL3_API_glBindSampler,
    GL3_API_glSamplerParameteri,
    GL3_API_glSamplerParameteriv,
    GL3_API_glSamplerParameterf,
    GL3_API_glSamplerParameterfv,
    GL3_API_glGetSamplerParameteriv,
    GL3_API_glGetSamplerParameterfv,
    GL3_API_glVertexAttribDivisor,
    GL3_API_glBindTransformFeedback,
    GL3_API_glDeleteTransformFeedbacks,
    GL3_API_glGenTransformFeedbacks,
    GL3_API_glIsTransformFeedback,
    GL3_API_glPauseTransformFeedback,
    GL3_API_glResumeTransformFeedback,
    GL3_API_glGetProgramBinary,
    GL3_API_glProgramBinary,
    GL3_API_glProgramParameteri,
    GL3_API_glInvalidateFramebuffer,
    GL3_API_glInvalidateSubFramebuffer,
    GL3_API_glTexStorage2D,
    GL3_API_glTexStorage3D,
    GL3_API_glGetInternalformativ,
    GL3_API_glEGLImageTargetTexture2DOES,
    GL3_API_glEGLImageTargetRenderbufferStorageOES,
    GL3_API_glMultiDrawArraysEXT,
    GL3_API_glMultiDrawElementsEXT,
    GL3_API_glMapBufferOES,
    GL3_API_glUnmapBufferOES,
    GL3_API_glDiscardFramebufferEXT,
    GL3_API_glFramebufferTexture2DMultisampleEXT,
    GL3_API_glTexDirectVIV,
    GL3_API_glTexDirectInvalidateVIV,
    GL3_API_glTexDirectVIVMap,
    GL3_API_glTexDirectTiledMapVIV,
    GL3_API_glGetBufferPointervOES,
    GL3_API_glGetProgramBinaryOES,
    GL3_API_glProgramBinaryOES,
    GL3_API_glGenQueriesEXT,
    GL3_API_glDeleteQueriesEXT,
    GL3_API_glIsQueryEXT,
    GL3_API_glBeginQueryEXT,
    GL3_API_glEndQueryEXT,
    GL3_API_glGetQueryivEXT,
    GL3_API_glGetQueryObjectuivEXT,
    GL3_API_glRenderbufferStorageMultisampleEXT,
    GL3_API_glGetGraphicsResetStatusEXT,
    GL3_API_glReadnPixelsEXT,
    GL3_API_glGetnUniformfvEXT,
    GL3_API_glGetnUniformivEXT,
    GL3_API_glDispatchCompute,
    GL3_API_glDispatchComputeIndirect,
    GL3_API_glDrawArraysIndirect,
    GL3_API_glDrawElementsIndirect,
    GL3_API_glFramebufferParameteri,
    GL3_API_glGetFramebufferParameteriv,
    GL3_API_glGetProgramInterfaceiv,
    GL3_API_glGetProgramResourceIndex,
    GL3_API_glGetProgramResourceName,
    GL3_API_glGetProgramResourceiv,
    GL3_API_glGetProgramResourceLocation,
    GL3_API_glUseProgramStages,
    GL3_API_glActiveShaderProgram,
    GL3_API_glCreateShaderProgramv,
    GL3_API_glBindProgramPipeline,
    GL3_API_glDeleteProgramPipelines,
    GL3_API_glGenProgramPipelines,
    GL3_API_glIsProgramPipeline,
    GL3_API_glGetProgramPipelineiv,
    GL3_API_glProgramUniform1i,
    GL3_API_glProgramUniform2i,
    GL3_API_glProgramUniform3i,
    GL3_API_glProgramUniform4i,
    GL3_API_glProgramUniform1ui,
    GL3_API_glProgramUniform2ui,
    GL3_API_glProgramUniform3ui,
    GL3_API_glProgramUniform4ui,
    GL3_API_glProgramUniform1f,
    GL3_API_glProgramUniform2f,
    GL3_API_glProgramUniform3f,
    GL3_API_glProgramUniform4f,
    GL3_API_glProgramUniform1iv,
    GL3_API_glProgramUniform2iv,
    GL3_API_glProgramUniform3iv,
    GL3_API_glProgramUniform4iv,
    GL3_API_glProgramUniform1uiv,
    GL3_API_glProgramUniform2uiv,
    GL3_API_glProgramUniform3uiv,
    GL3_API_glProgramUniform4uiv,
    GL3_API_glProgramUniform1fv,
    GL3_API_glProgramUniform2fv,
    GL3_API_glProgramUniform3fv,
    GL3_API_glProgramUniform4fv,
    GL3_API_glProgramUniformMatrix2fv,
    GL3_API_glProgramUniformMatrix3fv,
    GL3_API_glProgramUniformMatrix4fv,
    GL3_API_glProgramUniformMatrix2x3fv,
    GL3_API_glProgramUniformMatrix3x2fv,
    GL3_API_glProgramUniformMatrix2x4fv,
    GL3_API_glProgramUniformMatrix4x2fv,
    GL3_API_glProgramUniformMatrix3x4fv,
    GL3_API_glProgramUniformMatrix4x3fv,
    GL3_API_glValidateProgramPipeline,
    GL3_API_glGetProgramPipelineInfoLog,
    GL3_API_glBindImageTexture,
    GL3_API_glGetBooleani_v,
    GL3_API_glMemoryBarrier,
    GL3_API_glMemoryBarrierByRegion,
    GL3_API_glTexStorage2DMultisample,
    GL3_API_glGetMultisamplefv,
    GL3_API_glSampleMaski,
    GL3_API_glGetTexLevelParameteriv,
    GL3_API_glGetTexLevelParameterfv,
    GL3_API_glBindVertexBuffer,
    GL3_API_glVertexAttribFormat,
    GL3_API_glVertexAttribIFormat,
    GL3_API_glVertexAttribBinding,
    GL3_API_glVertexBindingDivisor,

    /* EGL 1.4 functions */
    EGL_API_eglGetError,
    EGL_API_eglGetDisplay,
    EGL_API_eglInitialize,
    EGL_API_eglTerminate,
    EGL_API_eglQueryString,
    EGL_API_eglGetConfigs,
    EGL_API_eglChooseConfig,
    EGL_API_eglGetConfigAttrib,
    EGL_API_eglCreateWindowSurface,
    EGL_API_eglCreatePbufferSurface,
    EGL_API_eglCreatePixmapSurface,
    EGL_API_eglDestroySurface,
    EGL_API_eglQuerySurface,
    EGL_API_eglBindAPI,
    EGL_API_eglQueryAPI,
    EGL_API_eglWaitClient,
    EGL_API_eglReleaseThread,
    EGL_API_eglCreatePbufferFromClientBuffer,
    EGL_API_eglSurfaceAttrib,
    EGL_API_eglBindTexImage,
    EGL_API_eglReleaseTexImage,
    EGL_API_eglSwapInterval,
    EGL_API_eglCreateContext,
    EGL_API_eglDestroyContext,
    EGL_API_eglMakeCurrent,
    EGL_API_eglGetCurrentContext,
    EGL_API_eglGetCurrentSurface,
    EGL_API_eglGetCurrentDisplay,
    EGL_API_eglQueryContext,
    EGL_API_eglWaitGL,
    EGL_API_eglWaitNative,
    EGL_API_eglSwapBuffers,
    EGL_API_eglCopyBuffers,
    EGL_API_eglGetProcAddress,
    EGL_API_eglCreateImageKHR,
    EGL_API_eglDestroyImageKHR,
    EGL_API_eglCreateSyncKHR,
    EGL_API_eglDestroySyncKHR,
    EGL_API_eglClientWaitSyncKHR,
    EGL_API_eglSignalSyncKHR,
    EGL_API_eglGetSyncAttribKHR,
    EGL_API_eglPatchID,
    EGL_API_eglLockSurfaceKHR,
    EGL_API_eglUnlockSurfaceKHR,

    /* ES1.1 functions */
    GL1_API_glAlphaFunc,
    GL1_API_glClearColor,
    GL1_API_glClearDepthf,
    GL1_API_glClipPlanef,
    GL1_API_glColor4f,
    GL1_API_glDepthRangef,
    GL1_API_glFogf,
    GL1_API_glFogfv,
    GL1_API_glFrustumf,
    GL1_API_glGetClipPlanef,
    GL1_API_glGetFloatv,
    GL1_API_glGetLightfv,
    GL1_API_glGetMaterialfv,
    GL1_API_glGetTexEnvfv,
    GL1_API_glGetTexParameterfv,
    GL1_API_glLightModelf,
    GL1_API_glLightModelfv,
    GL1_API_glLightf,
    GL1_API_glLightfv,
    GL1_API_glLineWidth,
    GL1_API_glLoadMatrixf,
    GL1_API_glMaterialf,
    GL1_API_glMaterialfv,
    GL1_API_glMultMatrixf,
    GL1_API_glMultiTexCoord4f,
    GL1_API_glNormal3f,
    GL1_API_glOrthof,
    GL1_API_glPointParameterf,
    GL1_API_glPointParameterfv,
    GL1_API_glPointSize,
    GL1_API_glPolygonOffset,
    GL1_API_glRotatef,
    GL1_API_glScalef,
    GL1_API_glTexEnvf,
    GL1_API_glTexEnvfv,
    GL1_API_glTexParameterf,
    GL1_API_glTexParameterfv,
    GL1_API_glTranslatef,
    GL1_API_glActiveTexture,
    GL1_API_glAlphaFuncx,
    GL1_API_glBindBuffer,
    GL1_API_glBindTexture,
    GL1_API_glBlendFunc,
    GL1_API_glBufferData,
    GL1_API_glBufferSubData,
    GL1_API_glClear,
    GL1_API_glClearColorx,
    GL1_API_glClearDepthx,
    GL1_API_glClearStencil,
    GL1_API_glClientActiveTexture,
    GL1_API_glClipPlanex,
    GL1_API_glColor4ub,
    GL1_API_glColor4x,
    GL1_API_glColorMask,
    GL1_API_glColorPointer,
    GL1_API_glCompressedTexImage2D,
    GL1_API_glCompressedTexSubImage2D,
    GL1_API_glCopyTexImage2D,
    GL1_API_glCopyTexSubImage2D,
    GL1_API_glCullFace,
    GL1_API_glDeleteBuffers,
    GL1_API_glDeleteTextures,
    GL1_API_glDepthFunc,
    GL1_API_glDepthMask,
    GL1_API_glDepthRangex,
    GL1_API_glDisable,
    GL1_API_glDisableClientState,
    GL1_API_glDrawArrays,
    GL1_API_glDrawElements,
    GL1_API_glEnable,
    GL1_API_glEnableClientState,
    GL1_API_glFinish,
    GL1_API_glFlush,
    GL1_API_glFogx,
    GL1_API_glFogxv,
    GL1_API_glFrontFace,
    GL1_API_glFrustumx,
    GL1_API_glGetBooleanv,
    GL1_API_glGetBufferParameteriv,
    GL1_API_glGetClipPlanex,
    GL1_API_glGenBuffers,
    GL1_API_glGenTextures,
    GL1_API_glGetError,
    GL1_API_glGetFixedv,
    GL1_API_glGetIntegerv,
    GL1_API_glGetLightxv,
    GL1_API_glGetMaterialxv,
    GL1_API_glGetPointerv,
    GL1_API_glGetString,
    GL1_API_glGetTexEnviv,
    GL1_API_glGetTexEnvxv,
    GL1_API_glGetTexParameteriv,
    GL1_API_glGetTexParameterxv,
    GL1_API_glHint,
    GL1_API_glIsBuffer,
    GL1_API_glIsEnabled,
    GL1_API_glIsTexture,
    GL1_API_glLightModelx,
    GL1_API_glLightModelxv,
    GL1_API_glLightx,
    GL1_API_glLightxv,
    GL1_API_glLineWidthx,
    GL1_API_glLoadIdentity,
    GL1_API_glLoadMatrixx,
    GL1_API_glLogicOp,
    GL1_API_glMaterialx,
    GL1_API_glMaterialxv,
    GL1_API_glMatrixMode,
    GL1_API_glMultMatrixx,
    GL1_API_glMultiTexCoord4x,
    GL1_API_glNormal3x,
    GL1_API_glNormalPointer,
    GL1_API_glOrthox,
    GL1_API_glPixelStorei,
    GL1_API_glPointParameterx,
    GL1_API_glPointParameterxv,
    GL1_API_glPointSizex,
    GL1_API_glPolygonOffsetx,
    GL1_API_glPopMatrix,
    GL1_API_glPushMatrix,
    GL1_API_glReadPixels,
    GL1_API_glRotatex,
    GL1_API_glSampleCoverage,
    GL1_API_glSampleCoveragex,
    GL1_API_glScalex,
    GL1_API_glScissor,
    GL1_API_glShadeModel,
    GL1_API_glStencilFunc,
    GL1_API_glStencilMask,
    GL1_API_glStencilOp,
    GL1_API_glTexCoordPointer,
    GL1_API_glTexEnvi,
    GL1_API_glTexEnvx,
    GL1_API_glTexEnviv,
    GL1_API_glTexEnvxv,
    GL1_API_glTexImage2D,
    GL1_API_glTexParameteri,
    GL1_API_glTexParameterx,
    GL1_API_glTexParameteriv,
    GL1_API_glTexParameterxv,
    GL1_API_glTexSubImage2D,
    GL1_API_glTranslatex,
    GL1_API_glVertexPointer,
    GL1_API_glViewport,
    GL1_API_glEGLImageTargetTexture2DOES,
    GL1_API_glMapBufferOES,
    GL1_API_glUnmapBufferOES,
    GL1_API_glPointSizePointerOES,
    GL1_API_glCurrentPaletteMatrixOES,
    GL1_API_glLoadPaletteFromModelViewMatrixOES,
    GL1_API_glMatrixIndexPointerOES,
    GL1_API_glWeightPointerOES,
    GL1_API_glBlendEquationSeparateOES,
    GL1_API_glBlendFuncSeparateOES,
    GL1_API_glBlendEquationOES,
    GL1_API_glGetBufferPointervOES,
    GL1_API_glDrawTexsOES,
    GL1_API_glDrawTexiOES,
    GL1_API_glDrawTexxOES,
    GL1_API_glDrawTexsvOES,
    GL1_API_glDrawTexivOES,
    GL1_API_glDrawTexxvOES,
    GL1_API_glDrawTexfOES,
    GL1_API_glDrawTexfvOES,
    GL1_API_glIsRenderbufferOES,
    GL1_API_glBindRenderbufferOES,
    GL1_API_glDeleteRenderbuffersOES,
    GL1_API_glGenRenderbuffersOES,
    GL1_API_glRenderbufferStorageOES,
    GL1_API_glGetRenderbufferParameterivOES,
    GL1_API_glIsFramebufferOES,
    GL1_API_glBindFramebufferOES,
    GL1_API_glDeleteFramebuffersOES,
    GL1_API_glGenFramebuffersOES,
    GL1_API_glCheckFramebufferStatusOES,
    GL1_API_glFramebufferRenderbufferOES,
    GL1_API_glFramebufferTexture2DOES,
    GL1_API_glGetFramebufferAttachmentParameterivOES,
    GL1_API_glGenerateMipmapOES,
    GL1_API_glEGLImageTargetRenderbufferStorageOES,
    GL1_API_glMultiDrawArraysEXT,
    GL1_API_glMultiDrawElementsEXT,

    GLES_FUNCTION_TOTAL_NUMBER
} GLESAPIIndex;

#endif // _TYPES_H
